'use client'

import { useState } from 'react'
import type { ConsumerWinery } from '../types/consumer'

function QuickTile({ icon, label, value, tone='plum' }: {icon:string;label:string;value?:string|null;tone?:string}) { return <article className={`quick-tile tone-${tone}`}><div className="quick-icon">{icon}</div><div><span>{label}</span><strong>{value ?? 'Not yet verified'}</strong></div></article> }
function Fact({label,value}:{label:string;value?:string|null}) { return <div className="fact"><span>{label}</span><strong>{value ?? 'Not yet verified'}</strong></div> }
const imgs=['https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=80']
const happenings={Today:[{time:'5:30 PM',title:'Golden-hour tasting',type:'Tasting experience',where:'Main patio',price:'Included with tasting',booking:'Walk-ins welcome',image:imgs[0]}],Tomorrow:[{time:'6:00 PM',title:'Live music on the patio',type:'Live music',where:'Vineyard patio',price:'No cover shown',booking:'Seating first come',image:imgs[1]}],'This Weekend':[{time:'SAT · 12 PM',title:'Weekend wine + food pairing',type:'Wine + food',where:'Restaurant terrace',price:'$65 · illustrative',booking:'Reservations recommended',image:imgs[2]},{time:'SUN · 11 AM',title:'Sunday brunch experience',type:'Dining',where:'Restaurant',price:'À la carte',booking:'Reservations recommended',image:imgs[0]}],'Next 7 Days':[{time:'FRI · 6 PM',title:'Live music',type:'Live music',where:'Patio',price:'No cover shown',booking:'Walk-ins',image:imgs[1]},{time:'SUN · 11 AM',title:'Brunch',type:'Dining',where:'Restaurant',price:'À la carte',booking:'Reserve ahead',image:imgs[2]},{time:'WED · 3 PM',title:'Winery tour',type:'Tour',where:'Tasting room',price:'$35 · illustrative',booking:'Reservation required',image:imgs[0]}]}
export function WineryProfile({winery:w}:{winery:ConsumerWinery}){
 const isDoffo=w.id==='doffo'; const [tab,setTab]=useState<keyof typeof happenings>('This Weekend'); const heroStyle=w.presentation.heroImage?{backgroundImage:`url(${w.presentation.heroImage})`}:undefined; const food=w.vinny.quickLook.find(x=>x.key==='food')?.value; const known=w.presentation.knownFor.slice(0,3); const gallery=isDoffo?['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1528823872057-9c018a7a7553?auto=format&fit=crop&w=1000&q=80']:['https://images.unsplash.com/photo-1473973266408-ed4e27abdd47?auto=format&fit=crop&w=1400&q=80','https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1566995541428-f2246c17cda1?auto=format&fit=crop&w=1000&q=80']; const mix=isDoffo?[72,18,7,3]:[66,24,7,3]; const portfolio=isDoffo?['Cabernet Sauvignon','Malbec','Zinfandel','Syrah','Red blends','Sauvignon Blanc','Rosé']:['Cabernet Franc','Cabernet Sauvignon','Syrah','Grenache','Red blends','Sauvignon Blanc','Viognier','Rosé'];
 const quick=<div className="quick-tile-grid"><QuickTile icon="🍷" label="Tasting" value={isDoffo?'Relaxed, personality-led':'Hosted, unhurried'}/><QuickTile icon="$" label="Tasting price" value="$30–$45 · illustrative" tone="gold"/><QuickTile icon="◷" label="Reservations" value={w.planning.reservations} tone="teal"/><QuickTile icon="🍽" label="Food" value={food} tone="rose"/><QuickTile icon="⏱" label="Visit length" value={w.planning.visitLength} tone="blue"/><QuickTile icon="👥" label="Groups" value={w.planning.groups} tone="grape"/></div>;
 return <main className="founder-modern traveler-profile"><div className="demo-banner">OUT IN THE VINES · TRAVELER PROFILE POC · PROTOTYPE DATA</div><header className="topbar"><a className="brand" href="/"><span className="brand-mark">O</span><span className="brand-copy"><strong>Out in the Vines</strong><small>TEMECULA WINE COUNTRY</small></span></a><nav className="desktop-nav"><a href="#happening">Happening</a><a href="#wine">Wine</a><a href="#feel">Experience</a><a href="#plan">Plan</a></nav><div className="specimen-switcher"><a href="/">Leoness</a><a href="/doffo">Doffo</a></div></header>
 <section className="winery-hero" style={heroStyle}><div className="hero-welcome"><span className="welcome-icon">V</span><div><small>VINNY WELCOME</small><strong>Review in progress</strong></div></div><div className="winery-hero-content"><p className="eyebrow gold">{w.identity.subregion}</p><h1>{w.identity.name}</h1><p>{w.presentation.shortDescription}</p><div className="hero-tags">{w.presentation.vibeLabels.map(x=><span key={x}>{x}</span>)}</div><div className="hero-contact"><span>◷ Thu 11 AM–6 PM · prototype</span><span>⌖ Temecula Wine Country · address in review</span><span>☎ (951) 555-0142 · prototype</span></div></div></section>
 <div className="mobile-quick"><p className="eyebrow gold">QUICK LOOK</p>{quick}</div>
 <section className="section traveler-shell"><div className="traveler-main"><section className="decision-card"><div className="vinny-intro"><div className="vinny-badge">V</div><div><p className="eyebrow teal">VINNY’S TAKE</p><div className="verdict">“{w.vinny.verdict}”</div></div></div><div className="decision-fit"><div><span>BEST KNOWN FOR</span><strong>{known.join(' · ')}</strong></div><div><span>BEST FOR</span><strong>{w.presentation.vibeLabels.slice(0,3).join(' · ')}</strong></div><div><span>PLAN AROUND</span><strong>{w.planning.reservations}</strong></div></div></section>
 <section id="happening" className="traveler-section"><div className="section-head"><div><p className="eyebrow teal">WHAT’S HAPPENING</p><h2>Make the timing part of the experience.</h2></div></div><div className="date-tabs">{(Object.keys(happenings) as (keyof typeof happenings)[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="event-card-grid">{happenings[tab].map(e=><article className="event-card" key={e.time+e.title}><div className="event-image" style={{backgroundImage:`url(${e.image})`}}><span>{e.time}</span></div><div className="event-copy"><small className="event-type">{e.type}</small><strong>{e.title}</strong><div className="event-details"><span>⌖ {e.where}</span><span>◈ {e.price}</span><span>◷ {e.booking}</span></div><button>Full details →</button></div></article>)}</div><button className="text-link">View full event calendar →</button></section>
 <section id="wine" className="wine-portfolio traveler-section"><div className="section-head"><div><p className="eyebrow gold">WINE PORTFOLIO</p><h2>What does this winery pour?</h2></div></div><div className="wine-overview"><div className="donut" style={{background:`conic-gradient(#6f234e 0 ${mix[0]}%,#d9c56f ${mix[0]}% ${mix[0]+mix[1]}%,#d98596 ${mix[0]+mix[1]}% ${mix[0]+mix[1]+mix[2]}%,#4f8b82 ${mix[0]+mix[1]+mix[2]}% 100%)`}}><div><strong>{mix[0]}%</strong><span>Red</span></div></div><div className="wine-mix"><div><i className="swatch red"/><strong>{mix[0]}% Red</strong><span>reported portfolio</span></div><div><i className="swatch white"/><strong>{mix[1]}% White</strong><span>reported portfolio</span></div><div><i className="swatch rose"/><strong>{mix[2]}% Rosé</strong><span>reported portfolio</span></div><div><i className="swatch other"/><strong>{mix[3]}% Other</strong><span>sparkling / dessert / other</span></div></div></div><div className="portfolio-breakdown"><strong>Portfolio includes</strong><div className="tags">{portfolio.map(x=><span className="tag" key={x}>{x}</span>)}</div></div><p className="source-note">Prototype percentages illustrate a future count of currently reported wines by style—not production volume.</p><button className="text-link">Explore full wine portfolio →</button></section>
 <div className="image-story-grid"><img src={gallery[0]} alt="Winery experience prototype"/><div><img src={gallery[1]} alt="Wine prototype"/><img src={gallery[2]} alt="Winery atmosphere prototype"/></div></div><section id="feel" className="traveler-section"><p className="eyebrow plum">THE EXPERIENCE</p><h2>What it feels like to spend time here.</h2><p className="experience-summary">{w.domains.experiences?.summary??w.presentation.shortDescription}</p></section>
 <section className="traveler-section split-travel"><article className="food-card"><p className="eyebrow gold">FOOD & DINING</p><h2>{food??'Food details in review'}</h2><div className="service-hours"><strong>Restaurant hours · prototype</strong><span>Thu–Sun · 11 AM–5 PM</span><span>Kitchen closes 60 min before winery</span></div><p>{w.domains.food?.summary??'Current dining details are still being verified.'}</p><div className="tags"><span className="tag">Reservations recommended</span><span className="tag">Full menu</span><span className="tag">Dietary details in review</span></div><button className="text-link">Menu, hours & reservations →</button></article><article><p className="eyebrow plum">SPACES & GROUPS</p><h2>Bringing your people?</h2><p>{w.planning.groups}</p><div className="tags"><span className="tag">Outdoor</span><span className="tag">Indoor</span><span className="tag">Private events</span></div><button className="text-link">Group & private-event details →</button></article></section>
 <section id="plan" className="traveler-section plan-full"><p className="eyebrow gold">WINERY DETAILS</p><h2>Everything you need before you leave.</h2><div className="glance-grid"><Fact label="Today's hours" value="11 AM–6 PM · prototype"/><Fact label="Address" value="Temecula, CA · full address in review"/><Fact label="Phone" value="(951) 555-0142 · prototype"/><Fact label="Reservations" value={w.planning.reservations}/><Fact label="Parking" value="On-site · detail in review"/><Fact label="Accessibility" value="Details in review"/><Fact label="Kids" value="Policy in review"/><Fact label="Pets" value="Policy in review"/></div><div className="plan-actions"><button>♡ Save</button><button>＋ Add to My Day</button><a href={w.actions.directionsUrl??'#'}>Directions</a><button className="ask-vinny">Ask Vinny</button></div></section>
 <section className="founder-card"><p className="eyebrow gold">TWO HUSBANDS. TWO PALATES.</p><h2>Andrew & Antonio</h2><p className="founder-lead">{w.editorial.founderNote}</p></section></div>
 <aside className="plan-rail"><div className="welcome-rail"><div className="welcome-rail-head"><span className="welcome-icon">V</span><div><small>VINNY WELCOME</small><strong>Review in progress</strong></div></div><p>{w.welcome.publicSummary}</p><button className="text-link">Welcome Report →</button></div><div className="rail-quick"><p className="eyebrow gold">QUICK LOOK</p>{quick}</div><div className="plan-rail-card"><strong>Plan this stop</strong><small>◷ Today · 11 AM–6 PM</small><small>⌖ Temecula Wine Country</small><small>☎ (951) 555-0142</small><button>♡ Save</button><button>＋ Add to My Day</button><a href={w.actions.directionsUrl??'#'}>Directions</a><button className="ask-vinny">Ask Vinny</button></div></aside></section><p className="source-note traveler-source">POC only. Hours, phone, pricing, portfolio mix and events include illustrative data until certified Vinny data is connected.</p><nav className="bottom-nav"><a href="#happening">Happening</a><a href="#wine">Wine</a><button className="ask-vinny">Ask Vinny</button></nav></main>
}
